### PR TITLE
feat: support pnpm

### LINKED ISSUE #9: Adding pnpm support
Adding [pnpm](https://github.com/pnpm/pnpm) support should be really easy.

I see currently this tool checks for a lockfile to decide what pm should be used for installation. pnpm has its own lockfile called `shrinkwrap.yaml`.

Alternatively, [which-pm](https://github.com/zkochan/which-pm) can be used, which will correctly identify the pm even when installing was done w/o a lockfile creation

### PR DESCRIPTION
**Pull request by zkochan**
There are no tests, so I tested this manually.
(if someone would like to try it, use the beta version of husky. The current latest version of husky does not work with pnpm)

close #9

### CODE REVIEW

**Comment by frontsideair** [comment]
Offtopic, I just noticed you're the author of pnpm. 😂 I didn't have time to check out the project earlier, looks like it's pretty fast! I'd like to give it a try, but the project I'm working on translates node dependencies to Nix. (A deterministic package manager for the whole system, an influence of ied.) Maybe we can make it work, I'd love to switch to pnpm. (The project we currently use is [yarn2nix](https://github.com/moretea/yarn2nix).)

**Comment by frontsideair** [comment]
I'll go ahead and merge this, readme can be edited separately. Thanks a lot!

**Comment by zkochan** [comment]
@frontsideair why do you translate Node dependencies to Nix? To save space, to have them in a central storage? In that case, you could use plain pnpm, it does that out of the box.

Anyway, feel free to open issues in pnpm repo or ask questions on [gitter](https://gitter.im/pnpm/pnpm)

**Comment by frontsideair** [comment]
Thanks, I'll investigate more before I'm ready to ask questions. 🍻

**Pull request merged**
