### PR TITLE
add support for package-lock.json

### PR DESCRIPTION
**Pull request by allybee**
Hi, thanks for the useful package! I added support for repos that use `npm` instead of `yarn`. I would have created an issue first, but you have that disabled... so feel free to reject this PR!

~Also, this kind of makes the package name obsolete so I changed it to a more general `lockfilehook`.~

### CODE REVIEW

**Comment by frontsideair** [comment]
You're very welcome! And sorry for the inconvenience with issues, looks like I went a little overboard when I was disabling Github features I didn't need. 😂 The PR looks solid and I want to merge it ASAP. But package name change so early on is a little intimidating, so I'll sleep on it. I don't know if I'll come up with anything better but who knows?

There's just a possible edge case if there is neither a `yarn.lock` nor a `package-lock.json`. I think we should quit immediately with an unobtrusive warning. Oh, and did you run prettier before committing? It's hard to tell by looking, but I'll add some scripts and a guide for contributing at some point.

Thanks for taking the time to implement this feature. Really appreciated!

**Comment by allybee** [comment]
Understood on the name change, I'll revert that so the purpose of this PR can be solely tied to the functionality!

**Comment by frontsideair** [comment]
I added warning for the case where no lockfile is found. What do you think @allybee?

**Comment by frontsideair** [comment]
Hooray!

**Pull request merged**
